theme_skin: "skin-green-light"
box_title_color: "green"
system_shortname: "KCL"
system_longname: "Kalkaska County Library"
nav_title: "KCL Stats"
wireless_ssid: "KCL"
include_whimsy: false
pubcomp_unique_users: false
item_types: [["audiobooks", "Audiobooks"], ["books", "Books"], ["childrensbooks", "Children's Books"], ["magazines", "Magazines"], ["music", "Music"], ["movies", "Movies"], ["other", "Other"]]
stats_url: "https://www.kalkaskalibrary.org/stats/"
site_title: "KCL Stats | Kalkaska County Library"
item_details_prefix: "https://catalog.kalkaskalibrary.org/main/details.json?id="
item_details_link_prefix: "https://catalog.kalkaskalibrary.org/main/details?id="
cover_image_prefix: "https://catalog.kalkaskalibrary.org/opac/extras/ac/jacket/large/r/"
multi_location: false
stats:
  - name: "circ_by_type_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/circ-by-type-12months.csv"
  - name: "collection_size"
    url: "https://www.kalkaskalibrary.org/statsdata/collection-size.csv"
  - name: "copies_added_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/copies-added-12months.csv"
  - name: "copies_withdrawn_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/copies-withdrawn-12months.csv"
  - name: "newusers_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/newusers-12months.csv"
  - name: "pubcomp_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/pubcomp-12months.csv"
  - name: "wireless_12months"
    url: "https://www.kalkaskalibrary.org/statsdata/wireless-12months.csv"
graphs:
  - name: "circ_weekly"
    url: "https://www.kalkaskalibrary.org/statsdata/circ-weekly.csv"
  - name: "wireless_weekly"
    url: "https://www.kalkaskalibrary.org/statsdata/wireless-weekly.csv"
  - name: "pubcomp_weekly"
    url: "https://www.kalkaskalibrary.org/statsdata/pubcomp-weekly.csv"
  - name: "newusers_weekly"
    url: "https://www.kalkaskalibrary.org/statsdata/newusers-weekly.csv"
lists:
  - name: "Books"
    url: "https://www.kalkaskalibrary.org/statsdata/top10books.csv"
  - name: "Movies"
    url: "https://www.kalkaskalibrary.org/statsdata/top10movies.csv"
  - name: "Kids"
    url: "https://www.kalkaskalibrary.org/statsdata/top10kids.csv"
locations:
  - name: "kcl"
    path_name: "all"
    pubcomp_name: "KCL"
    short_name: "Kalkaska"
    long_name: "Kalkaska County Library"
    evergreen_name: "KCL"
    background_color: "rgba(57,106,177,0.5)"
    border_color: "rgba(57,106,177,1)"
menu_items:
  - name: "Kalkaska"
    actual_path: "/view/all"
