system_shortname: "SBBDL"
system_longname: "Suttons Bay Bingham District Library"
nav_title: "SBBDL Stats"
wireless_ssid: "idk"
item_types: [["audiobooks", "Audiobooks"], ["books", "Books"], ["childrensbooks", "Children's Books"], ["magazines", "Magazines"], ["music", "Music"], ["movies", "Movies"], ["other", "Other"]]
stats_url: "https://www.sbbdl.org/stats/"
site_title: "SBBDL Stats | Suttons Bay Bingham District Library"
item_details_prefix: "https://catalog.sbbdl.org/main/details.json?id="
item_details_link_prefix: "https://catalog.sbbdl.org/main/details?id="
cover_image_prefix: "https://catalog.sbbdl.org/opac/extras/ac/jacket/large/r/"
circ_weekly_url: "https://www.sbbdl.org/statsdata/circ-weekly.csv"
circ_by_type_12months_url: "https://www.sbbdl.org/statsdata/circ-by-type-12months.csv"
collection_size_url: "https://www.sbbdl.org/statsdata/collection-size.csv"
copies_added_12months_url: "https://www.sbbdl.org/statsdata/copies-added-12months.csv"
copies_withdrawn_12months_url: "https://www.sbbdl.org/statsdata/copies-withdrawn-12months.csv"
newusers_weekly_url: "https://www.sbbdl.org/statsdata/newusers-weekly.csv"
newusers_12months_url: "https://www.sbbdl.org/statsdata/newusers-12months.csv"
pubcomp_weekly_url: "https://www.sbbdl.org/statsdata/pubcomp-weekly.csv"
pubcomp_12months_url: "https://www.sbbdl.org/statsdata/pubcomp-12months.csv"
soft_stat_questions_12months_url: "https://www.sbbdl.org/statsdata/soft-stat-questions-12months.csv"
wireless_weekly_url: "https://www.sbbdl.org/statsdata/wireless-weekly.csv"
wireless_12months_url: "https://www.sbbdl.org/statsdata/wireless-12months.csv"
toptens:
  - name: "books"
    url: "https://www.sbbdl.org/statsdata/top10books.csv"
  - name: "movies"
    url: "https://www.sbbdl.org/statsdata/top10movies.csv"
  - name: "childrensbooks"
    url: "https://www.sbbdl.org/statsdata/top10kids.csv"
multi_location: false
locations:
  - name: "sbbdl"
    path_name: "all"
    short_name: "Suttons Bay"
    long_name: "Suttons Bay Bingham District Library"
    evergreen_name: "SBBDL"
    background_color: "rgba(57,106,177,0.5)"
    border_color: "rgba(57,106,177,1)"
menu_items:
  - name: "Suttons Bay"
    actual_path: "/view/all"
