system_shortname: "SBBDL"
system_longname: "Suttons Bay Bingham District Library"
nav_title: "SBBDL Stats"
wireless_ssid: "idk"
include_whimsy: false
item_types: [["audiobooks", "Audiobooks"], ["books", "Books"], ["childrensbooks", "Children's Books"], ["magazines", "Magazines"], ["music", "Music"], ["movies", "Movies"], ["other", "Other"]]
stats_url: "https://www.sbbdl.org/stats/"
site_title: "SBBDL Stats | Suttons Bay Bingham District Library"
item_details_prefix: "https://catalog.sbbdl.org/main/details.json?id="
item_details_link_prefix: "https://catalog.sbbdl.org/main/details?id="
cover_image_prefix: "https://catalog.sbbdl.org/opac/extras/ac/jacket/large/r/"
multi_location: false
stats:
  - name: "circ_by_type_12months"
    url: "https://www.sbbdl.org/statsdata/circ-by-type-12months.csv"
  - name: "collection_size"
    url: "https://www.sbbdl.org/statsdata/collection-size.csv"
  - name: "copies_added_12months"
    url: "https://www.sbbdl.org/statsdata/copies-added-12months.csv"
  - name: "copies_withdrawn_12months"
    url: "https://www.sbbdl.org/statsdata/copies-withdrawn-12months.csv"
  - name: "newusers_12months"
    url: "https://www.sbbdl.org/statsdata/newusers-12months.csv"
  - name: "pubcomp_12months"
    url: "https://www.sbbdl.org/statsdata/pubcomp-12months.csv"
  - name: "wireless_12months"
    url: "https://www.sbbdl.org/statsdata/wireless-12months.csv"
graphs:
  - name: "circ_weekly"
    url: "https://www.sbbdl.org/statsdata/circ-weekly.csv"
  - name: "wireless_weekly"
    url: "https://www.sbbdl.org/statsdata/wireless-weekly.csv"
  - name: "pubcomp_weekly"
    url: "https://www.sbbdl.org/statsdata/pubcomp-weekly.csv"
  - name: "newusers_weekly"
    url: "https://www.sbbdl.org/statsdata/newusers-weekly.csv"
lists:
  - name: "Books"
    url: "https://www.sbbdl.org/statsdata/top10books.csv"
  - name: "Movies"
    url: "https://www.sbbdl.org/statsdata/top10movies.csv"
  - name: "Kids"
    url: "https://www.sbbdl.org/statsdata/top10kids.csv"
locations:
  - name: "sbbdl"
    path_name: "all"
    short_name: "Suttons Bay"
    long_name: "Suttons Bay Bingham District Library"
    evergreen_name: "SBBDL"
    background_color: "rgba(57,106,177,0.5)"
    border_color: "rgba(57,106,177,1)"
menu_items:
  - name: "Suttons Bay"
    actual_path: "/view/all"
