system_shortname: "TADL"
system_longname: "Traverse Area District Library"
brand_logo: "whitelogo.png"
nav_title: "TADL Stats"
wireless_ssid: "tadl-patron-wireless"
item_types: [["audiobooks", "Audiobooks"], ["books", "Books"], ["childrensbooks", "Children's Books"], ["magazines", "Magazines"], ["music", "Music"], ["movies", "Movies"], ["puppets", "Puppets"], ["other", "Other"]]
stats_url: "https://www.tadl.org/stats/"
site_title: "TADL Stats | Traverse Area District Library"
item_details_prefix: "https://catalog.tadl.org/main/details.json?id="
item_details_link_prefix: "https://catalog.tadl.org/main/details?id="
cover_image_prefix: "https://catalog.tadl.org/opac/extras/ac/jacket/large/r/"
circ_weekly_url: "https://www.tadl.org/statsdata/tadl/circ-weekly.csv"
circ_by_type_12months_url: "https://www.tadl.org/statsdata/tadl/circ-by-type-12months.csv"
collection_size_url: "https://www.tadl.org/statsdata/tadl/collection-size.csv"
copies_added_12months_url: "https://www.tadl.org/statsdata/tadl/copies-added-12months.csv"
copies_withdrawn_12months_url: "https://www.tadl.org/statsdata/tadl/copies-withdrawn-12months.csv"
newusers_weekly_url: "https://www.tadl.org/statsdata/tadl/newusers-weekly.csv"
newusers_12months_url: "https://www.tadl.org/statsdata/tadl/newusers-12months.csv"
pubcomp_weekly_url: "https://www.tadl.org/statsdata/tadl/pubcomp-weekly.csv"
pubcomp_12months_url: "https://www.tadl.org/statsdata/tadl/pubcomp-12months.csv"
soft_stat_questions_12months_url: "https://www.tadl.org/statsdata/tadl/soft-stat-questions-12months.csv"
top10books_url: "https://www.tadl.org/statsdata/tadl/top10books.csv"
top10movies_url: "https://www.tadl.org/statsdata/tadl/top10movies.csv"
top10music_url: "https://www.tadl.org/statsdata/tadl/top10music.csv"
wireless_weekly_url: "https://www.tadl.org/statsdata/tadl/wireless-weekly.csv"
wireless_12months_url: "https://www.tadl.org/statsdata/tadl/wireless-12months.csv"
multi_location: true
locations:
  - name: "wood"
    path_name: "traversecity"
    short_name: "Woodmere"
    long_name: "Traverse City Library"
    evergreen_name: "TADL-WOOD"
    background_color: "rgba(57,106,177,0.5)"
    border_color: "rgba(57,106,177,1)"
  - name: "ebb"
    path_name: "eastbay"
    short_name: "East Bay"
    long_name: "East Bay Branch Library"
    evergreen_name: "TADL-EBB"
    background_color: "rgba(218,124,48,0.5)"
    border_color: "rgba(218,124,48,1)"
  - name: "flpl"
    path_name: "fifelake"
    short_name: "Fife Lake"
    long_name: "Fife Lake Public Library"
    evergreen_name: "TADL-FLPL"
    background_color: "rgba(62,150,81,0.5)"
    border_color: "rgba(62,150,81,1)"
  - name: "ipl"
    path_name: "interlochen"
    short_name: "Interlochen"
    long_name: "Interlochen Public Library"
    evergreen_name: "TADL-IPL"
    background_color: "rgba(204,37,41,0.5)"
    border_color: "rgba(204,37,41,1)"
  - name: "kbl"
    path_name: "kingsley"
    short_name: "Kingsley"
    long_name: "Kingsley Branch Library"
    evergreen_name: "TADL-KBL"
    background_color: "rgba(83,81,84,0.5)"
    border_color: "rgba(83,81,84,1)"
  - name: "pcl"
    path_name: "peninsula"
    short_name: "Peninsula"
    long_name: "Peninsula Community Library"
    evergreen_name: "TADL-PCL"
    background_color: "rgba(107,76,154,0.5)"
    border_color: "rgba(107,76,154,1)"
menu_items:
  - name: "All Locations"
    actual_path: "/view/all"
  - name: "East Bay"
    actual_path: "/view/eastbay"
  - name: "Fife Lake"
    actual_path: "/view/fifelake"
  - name: "Interlochen"
    actual_path: "/view/interlochen"
  - name: "Kingsley"
    actual_path: "/view/kingsley"
  - name: "Peninsula"
    actual_path: "/view/peninsula"
  - name: "Traverse City"
    actual_path: "/view/traversecity"
