theme_skin: "skin-blue-light"
box_title_color: "primary"
system_shortname: "TADL"
system_longname: "Traverse Area District Library"
nav_title: "TADL Stats"
wireless_ssid: "tadl-patron-wireless"
include_whimsy: true
logo: "https://old.tadl.org/logo.png"
show_about: true
pubcomp_unique_users: true
item_types: [["audiobooks", "Audiobooks"], ["books", "Books"], ["childrensbooks", "Children's Books"], ["magazines", "Magazines"], ["music", "Music"], ["movies", "Movies"], ["puppets", "Puppets"], ["other", "Other"]]
stats_url: "https://old.tadl.org/stats/"
site_title: "TADL Stats | Traverse Area District Library"
item_details_prefix: "https://catalog.tadl.org/main/details.json?id="
item_details_link_prefix: "https://catalog.tadl.org/main/details?id="
cover_image_prefix: "https://catalog.tadl.org/opac/extras/ac/jacket/large/r/"
stats:
  - name: "circ_by_type_12months"
    url: "https://old.tadl.org/statsdata/tadl/circ-by-type-12months.csv"
  - name: "collection_size"
    url: "https://old.tadl.org/statsdata/tadl/collection-size.csv"
  - name: "copies_added_12months"
    url: "https://old.tadl.org/statsdata/tadl/copies-added-12months.csv"
  - name: "copies_withdrawn_12months"
    url: "https://old.tadl.org/statsdata/tadl/copies-withdrawn-12months.csv"
  - name: "newusers_12months"
    url: "https://old.tadl.org/statsdata/tadl/newusers-12months.csv"
  - name: "pubcomp_12months"
    url: "https://old.tadl.org/statsdata/tadl/pubcomp-12months.csv"
  - name: "soft_stat_questions_12months"
    url: "https://old.tadl.org/statsdata/tadl/soft-stat-questions-12months.csv"
  - name: "wireless_12months"
    url: "https://old.tadl.org/statsdata/tadl/wireless-12months.csv"
graphs:
  - name: "circ_weekly"
    url: "https://old.tadl.org/statsdata/tadl/circ-weekly.csv"
  - name: "wireless_weekly"
    url: "https://old.tadl.org/statsdata/tadl/wireless-weekly.csv"
  - name: "pubcomp_weekly"
    url: "https://old.tadl.org/statsdata/tadl/pubcomp-weekly.csv"
  - name: "newusers_weekly"
    url: "https://old.tadl.org/statsdata/tadl/newusers-weekly.csv"
lists:
  - name: "Books"
    url: "https://old.tadl.org/statsdata/tadl/top10books.csv"
  - name: "Movies"
    url: "https://old.tadl.org/statsdata/tadl/top10movies.csv"
  - name: "Music"
    url: "https://old.tadl.org/statsdata/tadl/top10music.csv"
multi_location: true
locations:
  - name: "wood"
    path_name: "traversecity"
    pubcomp_name: "Woodmere"
    short_name: "Woodmere"
    long_name: "Traverse City Library"
    evergreen_name: "TADL-WOOD"
    background_color: "rgba(57,106,177,0.5)"
    border_color: "rgba(57,106,177,1)"
  - name: "ebb"
    path_name: "eastbay"
    pubcomp_name: "East Bay"
    short_name: "East Bay"
    long_name: "East Bay Branch Library"
    evergreen_name: "TADL-EBB"
    background_color: "rgba(218,124,48,0.5)"
    border_color: "rgba(218,124,48,1)"
  - name: "flpl"
    path_name: "fifelake"
    pubcomp_name: "Fife Lake"
    short_name: "Fife Lake"
    long_name: "Fife Lake Public Library"
    evergreen_name: "TADL-FLPL"
    background_color: "rgba(62,150,81,0.5)"
    border_color: "rgba(62,150,81,1)"
  - name: "ipl"
    path_name: "interlochen"
    pubcomp_name: "Interlochen"
    short_name: "Interlochen"
    long_name: "Interlochen Public Library"
    evergreen_name: "TADL-IPL"
    background_color: "rgba(204,37,41,0.5)"
    border_color: "rgba(204,37,41,1)"
  - name: "kbl"
    path_name: "kingsley"
    pubcomp_name: "Kingsley"
    short_name: "Kingsley"
    long_name: "Kingsley Branch Library"
    evergreen_name: "TADL-KBL"
    background_color: "rgba(83,81,84,0.5)"
    border_color: "rgba(83,81,84,1)"
  - name: "pcl"
    path_name: "peninsula"
    pubcomp_name: "Peninsula"
    short_name: "Peninsula"
    long_name: "Peninsula Community Library"
    evergreen_name: "TADL-PCL"
    background_color: "rgba(107,76,154,0.5)"
    border_color: "rgba(107,76,154,1)"
menu_items:
  - name: "All Locations"
    actual_path: "/view/all"
  - name: "East Bay"
    actual_path: "/view/eastbay"
  - name: "Fife Lake"
    actual_path: "/view/fifelake"
  - name: "Interlochen"
    actual_path: "/view/interlochen"
  - name: "Kingsley"
    actual_path: "/view/kingsley"
  - name: "Peninsula"
    actual_path: "/view/peninsula"
  - name: "Traverse City"
    actual_path: "/view/traversecity"
